### ISSUE TITLE
Cannot validate any output from the ITS Demo

### ISSUE THREAD

**Issue by lismore** [pvendil/c2c-common#1]
I modified the ITSDemo.java  file to write generated CA/Certs/Keys/Messages to a file.

![image](https://cloud.githubusercontent.com/assets/1145888/18918719/9f678c48-8593-11e6-85ec-9016253a455a.png)

The ITSDemo.java JUnit test passes -  output looks good 

![image](https://cloud.githubusercontent.com/assets/1145888/18918798/d43f635a-8593-11e6-9f9f-3fa0d3ef04ad.png)

I am trying to use the following site as referenced in the documentation to verify the output 

https://werkzeug.dcaiti.tu-berlin.de/etsi/ts103097/

No matter what data I enter here from the output of the ITSDemo test will not validate. Is there any more information on how /what to take from the generated output so that it can be successfully validated.  

best regards

Patrick

**Comment by lismore** [comment]
Ok found a solution,  

By calling Hex.encode on certificate.getEncoded() I was able to get the correct Hex to validate. 

new String(Hex.encode(rootCACertificate.getEncoded()))

```
File file2 = new File("c:\\pki\\LismoreRootCA1.crt");

                // if file doesnt exists, then create it
                if (!file2.exists()) {
                file2.createNewFile();
                }

                FileWriter fw2 = new FileWriter(file2.getAbsoluteFile());
                BufferedWriter bw2 = new BufferedWriter(fw2);
                bw2.write(new String(Hex.encode(rootCACertificate.getEncoded())));
                bw2.close();
```

**Comment by certservice-se-bambo** [comment]
Hi

Sorry for not responding earlier. I was on vacation and couldn't respond until today. Glad to hear that your fixed your problem. Let me know if you run into any other issues.
