### ISSUE TITLE
IEEE 1609.2 2016

### ISSUE THREAD

**Issue by hmusavi** [pvendil/c2c-common#2]
@pvendil 

I am looking for an implementation of IEEE 1609.2-2016. Your README states that this library supports 2015 version but IEEE 1609 was finalized on 3/1/2016. The previous US standard has been 2013. Does this mean that this product was developed based on preliminary specs? Would it work with the final version of the spec?

Thanks

**Comment by pvendil** [comment]
Hi
Sorry for the long delay in answer, but haven't worked on the library until it became more mature since the standards kept changing but have now updated it to IEEE 1609.2a 2017 Amendment.
