### ISSUE TITLE
COERBoolean

### ISSUE THREAD

**Issue by Tiagopinto96** [pvendil/c2c-common#3]
Hello @pvendil,

I have been analising the code and noticed that in the COEDBollean encoded structure the true and false values does not match what is expected by the ITU-T X.696 standard described in IEEE's Std 1609.2-2016. That document states:

> "The encoding of a Boolean value shall be a single octet. The octet value 0 denotes the Boolean value FALSE and a non-zero octet value denotes the Boolean value TRUE. NOTE - In CANONICAL-OER, only the octet value 'FF'H can be used to encode the value TRUE ... "

In your implementation's code the false value is FF'H and the true value is 00'H, shouldn't it be the opposite? 
Am i misunderstanding something or is there a bug in your implementation?

**Comment by pvendil** [comment]
Hi 
Sorry for the long delay in answer, but haven't worked on this project until the standards became more mature. You are corrent according to the COERBoolean and have updated in latest 2.0.0-beta1 release.
