### ISSUE TITLE
Source folder src/test/resources missing

### ISSUE THREAD

**Issue by AliKalsen** [pvendil/c2c-common#5]
Hi,

when building the project, eclipse returns an error stating that the above source folder is missing. This might be a reason why the tests don't run properly on my computer returing a Class.

However, when deleting the source folder from the build path or the classpath file, other errors occur, e.g. in the class COERBitString.groovy. I couldn't solve that error or even figure it out. Maybe you can help me @pvendil 

Cheers,

McLovin

**Comment by pvendil** [comment]
Hi

How did you import the project in eclipse, from pom.xml? I have seen that the maven pom is a bit faulty and it's on my todo list to migrate it into gradle.

It seems that you don't have groovy added to your project in eclipse. All the unit tests is written i groovy and spock framework and eclipse have to have groovy installed in the project.

**Comment by AliKalsen** [comment]
Hi,

thanks for the fast reply. Yes, I imported the project from pom.xml. Indeed, the maven pom seems to be faulty. However, I added groovy to the project, but Eclipse returns a lot of errors and doesn't build the project.

**Comment by AliKalsen** [comment]
Ok, I just deleted the dependencies in the pom file and inserted the jar files on my own.  The project now builds properly. However, there class EtsiTs103097Demo.java returns a DecoderException. Maybe, I will find a way to fix this. All the other tests run.

**Comment by pvendil** [comment]
The project have now migrated to a gradle build and should build properly now.
